"""Protocol definitions for exchange abstraction."""

from __future__ import annotations

from typing import Protocol

from auramaur.exchange.models import Market, Order, OrderBook, OrderResult, Signal


class MarketDiscovery(Protocol):
    """Protocol for market discovery and data retrieval."""

    async def get_markets(self, active: bool = True, limit: int = 100) -> list[Market]: ...
    async def get_market(self, market_id: str) -> Market | None: ...
    async def search_markets(self, query: str, limit: int = 50) -> list[Market]: ...
    async def close(self) -> None: ...


class ExchangeClient(Protocol):
    """Protocol for order execution on an exchange."""

    async def place_order(self, order: Order) -> OrderResult: ...
    async def get_order_book(self, market_id: str) -> OrderBook: ...
    async def get_order_status(self, order_id: str) -> OrderResult: ...
    async def cancel_order(self, order_id: str) -> bool: ...
    def prepare_order(
        self, signal: Signal, market: Market, position_size: float, is_live: bool
    ) -> Order | None: ...
    async def close(self) -> None: ...
